![banner](../../docs/figs/brand_identity/banner.png)

## **Pandas Basics**

Pandas is a powerful Python library for working with tabular data (data with labels/headers).

- It helps you read, organize, and analyze data easily.
- Main data structures are:
  - *Series*: a 1D labeled array
  - *DataFrame*: a 2D labeled table

## 1. Series

In [1]:
import pandas as pd

# Create a Series (1D labeled array)
s = pd.Series([10, 20, 30, 40], index=["a", "b", "c", "d"])
s

a    10
b    20
c    30
d    40
dtype: int64

In [2]:
# Access value by position (index)
print("\nValue at index 0:", s.iloc[0])  # 10

# Access value by label (label)
print("Value with label 'c':", s.loc["c"])  # 30

Value at index 0: 10
Value with label 'c': 30

## 2. DataFrame

In [4]:
# Create a dictionary
# It looks like a rotated table
data = {
    "Name": ["Alice", "Bob", "Charlie"], 
    "Age": [25, 30, 35],
    "City": ["New York", "Paris", "London"]
}

# Turn it to a DataFrame
df = pd.DataFrame(data)
df # display in jupyter notebook

      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   35    London

## 3. Accessing Data

#### Access column(s)

In [5]:
# Access column
df["Name"]

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [6]:
# Access columns
df[["Name", "Age"]]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

#### Access row(s)

In [7]:
# Access row
df.iloc[0]

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [8]:
# Access rows
df.iloc[[0,2]]

      Name  Age      City
0    Alice   25  New York
2  Charlie   35    London

In [9]:
# Access rows with range
df.iloc[0:2]

    Name  Age      City
0  Alice   25  New York
1    Bob   30     Paris

#### Access a value (cell)

In [10]:
data = {
    "Name": ["Alice", "Bob", "Charlie"], 
    "Age": [25, 30, 35],
    "City": ["New York", "Paris", "London"]
}

df = pd.DataFrame(data)
df

      Name  Age      City
0    Alice   25  New York
1      Bob   30     Paris
2  Charlie   35    London

In [11]:
# Using label-based .loc
print("Value at row 0, column 'Age':", df.loc[0, "Age"])  

# Using position-based .iloc
print("Value at row 1, column 'City':", df.iloc[1, 2])

Value at row 0, column 'Age': 25
Value at row 1, column 'City': Paris

## 4. Operating Data

#### Basic statistics for a column

In [12]:
print(df["Age"].mean())
print(df["Age"].median())
print(df["Age"].max())
print(df["Age"].min())

30.0
30.0
35
25

#### Filter rows

In [13]:
# Filter where Age > 28
df[df["Age"] > 28]  
# inner df[] evaluates which rows meet the condition
# outer df[] extracts the successful rows from the main DataFrame

      Name  Age    City
1      Bob   30   Paris
2  Charlie   35  London

#### Add a new column

In [14]:
df["Salary"] = [70000, 80000, 90000]
df

      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30     Paris   80000
2  Charlie   35    London   90000

#### Add a new row

In [15]:
df.loc[3] = ["David", 28, "Berlin", 60000]
df

      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30     Paris   80000
2  Charlie   35    London   90000
3    David   28    Berlin   60000

## 5. Export & Import Data

#### Saving DataFrame to CSV

In [16]:
df.to_csv("output.csv", index=False)  # index=False means row numbers are not saved
print("DataFrame saved to 'output.csv'")

DataFrame saved to 'output.csv'

#### Reading a CSV file into a DataFrame

In [17]:
df = pd.read_csv("output.csv") 
df.head() # showing the fisrt few ros of the dataframe

      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30     Paris   80000
2  Charlie   35    London   90000
3    David   28    Berlin   60000